filter:
    paths:
        - 'app/*'

checks:
    php:
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        parse_doc_comments: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        no_short_variable_names:
            minimum: '3'
        no_short_open_tag: true
        no_short_method_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_debug_code: true
        no_commented_out_code: true
        missing_arguments: true
        method_calls_on_non_object: true
        line_length:
            max_length: '200'
        encourage_single_quotes: true
        deprecated_code_usage: true
        comparison_always_same_result: true
        code_rating: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_todo_comments: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
        argument_type_checks: true

build:
    environment:
        php:
            version: 7.0.0
