language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

sudo: false

cache:
    directories:
        - node_modules

before_install:
  - nvm install 5.1

install:
  - travis_retry composer install
  - travis_retry npm install

before_script:
  - mkdir -p storage/framework/{cache,views,sessions}
  - touch database/database.sqlite
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan view:clear
  - php artisan optimize

script:
  - php artisan migrate --seed
  - gulp
  - vendor/bin/phpunit
